runtime: python311
service: legalease-backend
instance_class: F2

env_variables:
  ALLOWED_ORIGINS: "*"
  MOCK_AI: "true"
  PORT: "8080"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
  - url: /.*
    script: auto
    secure: always
